import type { Metadata } from 'next'
export const dynamic = 'force-dynamic' // https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { ThemeProvider } from '@/src/theme/ThemeProvider'
import { Header } from '@/src/features/layout/header'
const inter = Inter({ subsets: ['latin'] })
import NavaBarInformation from '@/src/features/layout/navBarInformation'
import NavBar from '@/src/features/layout/navBar'
import { getAuthSession } from '@/lib/auth'
import { userIsComplete } from '@/src/query/user.query'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode,
  modal?: React.ReactNode
}

export default async function RootLayout({
  children,
  modal
}: LayoutProps) {
  const session = await getAuthSession()
  return (
    <html lang="fr" className='h-full' suppressHydrationWarning>
      <body className={clsx(inter.className, 'bg-background h-full')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Header>
            {session ? <NavBar /> : <NavaBarInformation />}
          </Header>
          <main className='flex flex-col w-full h-full items-center'>
            {children}
          </main>
          {modal}
        </ThemeProvider>

      </body>
    </html>
  )
}
