import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { ThemeProvider } from '@/src/theme/ThemeProvider'
import { Header } from '@/src/features/layout/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode,
  modal?: React.ReactNode
}

export default function RootLayout({
  children,
  modal
}: LayoutProps) {
  return (
    <html lang="fr" className='h-full' suppressHydrationWarning>
      <body className={clsx(inter.className, 'bg-background h-full')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Header />
          <main className='flex flex-col w-full h-full items-center'>
            <div className='flex flex-col justify-center w-3/4'>
              {children}

            </div>
          </main>
          {modal}
        </ThemeProvider>

      </body>
    </html>
  )
}
