-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "isApproved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isOpen" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "isPending" BOOLEAN NOT NULL DEFAULT false;
