import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient(
    {
        log: [
            {
                emit: 'stdout',
                level: 'query',
            },
            {
                emit: 'stdout',
                level: 'error',
            },
            {
                emit: 'stdout',
                level: 'info',
            },
            {
                emit: 'stdout',
                level: 'warn',
            },
        ],
    }
)
import { Seed } from "./seedModel"

class OpsV00003Seed extends Seed {
    constructor(
        protected name: string,
        protected description: string,
        protected order: number,
        protected previousLabel: string
    ) {
        super(name, description, order, previousLabel)
    }

    async run() {
        const seedExist = await this.seedIsComplete()
        const previousStatus = await this.previousSeedIsComplete()
        try {
            if (previousStatus && !seedExist) {
                await this.seedUpdateStatus("pending")

                await prisma.dsn_OPS.createMany({
                    data: [
                        { id: "222222222", label: "MUTUELLE DE TEST" },
                        { id: "301862769", label: "MUTUELLE SMH" },
                        { id: "302476536", label: "LA MUTUELLE CATALANE" },
                        { id: "302655766", label: "ESPACE MUTUALISTE GIVORDIN" },
                        { id: "302766852", label: "MUTUELLE DE LA REGIE DES TRANSPORTS EN COMMUN DE L'AGGLOMERATION TROYENNE" },
                        { id: "302927553", label: "APICIL MUTUELLE" },
                        { id: "302976592", label: "AVENIR MUTUELLE" },
                        { id: "302981923", label: "MUTUELLE DES PROFESSIONS JUDICIAIRES" },
                        { id: "304580228", label: "MUTUELLE FAMILIALE DE NORMANDIE" },
                        { id: "308708650", label: "MCLR" },
                        { id: "309104099", label: "LA MUTUELLE VERTE" },
                        { id: "309244648", label: "MUTUELLE ENTRENOUS" },
                        { id: "310259221", label: "MUTUELLE D'IVRY (LA FRATERNELLE)" },
                        { id: "311799878", label: "AESIO MUTUELLE (ex ADREA MUTUELLE)" },
                        { id: "313309080", label: "LES MUTUELLES LIGERIENNES" },
                        { id: "313385882", label: "MUTUELLE ENSEMBLE" },
                        { id: "313389157", label: "MUTUELLE D ENTREPRISE DES ETABLISSEMENTS DU BON SAUVEUR" },
                        { id: "314559451", label: "MUTUELLE MARE GAILLARD" },
                        { id: "314685835", label: "MUTUELLE DES HOPITAUX DE LA VIENNE" },
                        { id: "314765546", label: "MUTUELLE DES CHEMINOTS DE LA REGION DE NANTES" },
                        { id: "315519231", label: "MUTUELLE LA CHOLETAISE" },
                        { id: "315652263", label: "MUTAVIE" },
                        { id: "317442176", label: "AESIO MUTUELLE (ex EOVI-MCD MUTUELLE)" },
                        { id: "319074779", label: "MUTUELLE CHEMINOTS DU NORD" },
                        { id: "320377906", label: "MUTUELLE GENERALE DE PREVOYANCE SOCIALE" },
                        { id: "324042621", label: "MUTUELLE DES TRANSPORTS" },
                        { id: "330929845", label: "MUTUELLE MFTSV" },
                        { id: "331901942", label: "MUTUELLE INTERPROFESSIONNELLE DE PREVOYANCE" },
                        { id: "331903757", label: "MUTUELLE ACCIDENTS DE LA CONFEDERATION GENERALE DES OEUVRES LAIQUES" },
                        { id: "333212561", label: "MUTUELLE DE PONTOISE" },
                        { id: "333333333", label: "MUTUELLE DES PATENTES ET LIBERAUX DE NOUVELLE CALEDONIE" },
                        { id: "337682660", label: "MUTUELLE GENERALE DE PREVOYANCE" },
                        { id: "339198939", label: "MUTAC" },
                        { id: "339358681", label: "MALAKOFF HUMANIS NATIONALE" },
                        { id: "340359900", label: "INTEGRANCE" },
                        { id: "342211265", label: "MUTUELLES DE LORRAINE" },
                        { id: "344304787", label: "UNION DES MUTUELLES DE LA REUNION" },
                        { id: "347391948", label: "MUTUELLE DU CHU ET HOPITAUX DU PUY DE DOME" },
                        { id: "348099789", label: "MUTUELLE PROVENCE ENTREPRISES" },
                        { id: "350873287", label: "MUTUELLE DES TERRITORIAUX ET HOSPITALIERS" },
                        { id: "351948237", label: "LA PROBITE" },
                        { id: "351956537", label: "MUTUELLE DE L'ENSEIGNEMENT CATHOLIQUE DE L'ANJOU" },
                        { id: "351963616", label: "MUTUELLE INTERENTREPRISE ERAM 526" },
                        { id: "352291561", label: "MUTUELLE MEUSREC" },
                        { id: "352502546", label: "MUTUELLE DU VAL DE SEVRE" },
                        { id: "352537369", label: "AMICALE DU PERSONNEL DE FLEURY MICHON SA" },
                        { id: "353171440", label: "MIAG - MUTUELLE INTERPROFESSIONNELLE ANTILLE GUYANNE" },
                        { id: "379718653", label: "MUTUELLE NATIONALE DES PERSONNELS AIR FRANCE" },
                        { id: "382046464", label: "MUTUELLE NATIONALE DU PERSONNEL DES ETABLISSEMENTS MICHELIN" },
                        { id: "383143617", label: "SOLIMUT MUTUELLE DE FRANCE" },
                        { id: "384253605", label: "MUTLOG GARANTIES" },
                        { id: "384513073", label: "MUTUELLE GENERALE DE PREVOYANCE ET D'ASSISTANCE" },
                        { id: "388213423", label: "MUTUELLE GENERALE SOLIDARITE DE LA REUNION" },
                        { id: "388213712", label: "MUTUELLE FAMILIALE DE LA REUNION" },
                        { id: "388887259", label: "MUTUELLE DES ELUS LOCAUX" },
                        { id: "390550986", label: "SOCIETE MUTUALISTE DU PERSONNEL ACTIF ET RETRAITE DE LA MARQUE" },
                        { id: "390730893", label: "MUTUELLE D'OUEST-FRANCE" },
                        { id: "390802619", label: "MUTUELLE LA SECURITE ASTURIENNE" },
                        { id: "390820058", label: "MUTUELLE D'ENTREPRISES SCHNEIDER ELECTRIC" },
                        { id: "390917953", label: "MUTUELLE DU BATIMENT ET DES TRAVAUX PUBLICS DU SUD EST" },
                        { id: "390998466", label: "MUTUELLE SAINT AUBANNAISE" },
                        { id: "391036183", label: "MUTUELLE DES SAPEURS POMPIERS DE PARIS" },
                        { id: "391322849", label: "MUTUELLE DE LA DEPECHE DU MIDI" },
                        { id: "391346236", label: "NUOMA MUTUELLE" },
                        { id: "391396397", label: "SOCIETE DE PREVOYANCE MUTUALISTE DU PERSONNEL DE LA BANQUE DE FRANCE" },
                        { id: "391398351", label: "MUTUELLE NATIONALE DES CONSTRUCTEURS ET ACCEDANTS A LA PROPRIETE" },
                        { id: "391399227", label: "GARANCE" },
                        { id: "391399326", label: "MUTUELLE EPC" },
                        { id: "391416591", label: "MGDF - MUTUELLE GOODYEAR DUNLOP FRANCE" },
                        { id: "391526225", label: "MUTUELLE SANTE EIFFAGE ENERGIE" },
                        { id: "391951357", label: "MUTUELLE DU PERSONNEL DES COLLECTIVITES TERRITORIALE DE LA REUNION" },
                        { id: "397742958", label: "MUTUELLE DE FRANCE DES HOSPITALIERS" },
                        { id: "405390238", label: "MUTUELLE DE FRANCE LOIRE FOREZ" },
                        { id: "407879709", label: "SOCIETE MUTUALISTE INTER-ENTREPRISES" },
                        { id: "413423005", label: "MUTUELLE LA FRANCE MARITIME" },
                        { id: "414494708", label: "SPHERIA VIE" },
                        { id: "419049499", label: "ENERGIE MUTUELLE" },
                        { id: "419320015", label: "MUTUELLE PREVOYANCE ET DE L'HABITAT DE LA REUNION" },
                        { id: "422801910", label: "MUTUELLE DES SPORTIFS" },
                        { id: "429873706", label: "BANQUE POPULAIRE MUTUALITE" },
                        { id: "430169342", label: "MUTUELLE DES PERSONNELS DU CH MONTPERRIN" },
                        { id: "430173336", label: "MUTUELLE DES EMPLOYES TERRITORIAUX DE SAINT RAPHAEL" },
                        { id: "430181123", label: "MUTUELLE DES PERSONNELS MARITIMES" },
                        { id: "430184507", label: "MUTUELLE DU PERSONNEL DES TRANSPORTS URBAINS DE CANNES - BUS AZUR" },
                        { id: "430270116", label: "MUTUELLE DE SAINT JUNIEN ET DES ENVIRONS" },
                        { id: "431282581", label: "SOLIMUT MUTUELLE PERSONNELS ORGANISMES SOCIAUX" },
                        { id: "431535327", label: "CPAM - SOCIETE MUTUALISTE INTERENTREPRISE DU PERSONNEL DES ORGANISMES SOCIAUX DU LOT" },
                        { id: "431643071", label: "MUTUELLE DE LA VERRERIE D'ALBI" },
                        { id: "431988021", label: "MUTUELLE EPARGNE RETRAITE" },
                        { id: "432162113", label: "MUTUELLE DES ANCIENS DES CHANTIERS LA ROCHELLE-PALLICE" },
                        { id: "432456788", label: "MUTUELLE DU PERSONNEL DES PORTS DU DETROIT" },
                        { id: "432674281", label: "MUTUELLE AIDE ET SOLIDARITE" },
                        { id: "432683787", label: "MUTUELLE DE PREVOYANCE ET DE SANTE" },
                        { id: "433087806", label: "MUTUELLE AVENIR SANTE" },
                        { id: "434243085", label: "MUTUELLE OCIANE MATMUT" },
                        { id: "437732191", label: "SOCIETE MUTUALISTE DU SALEVE" },
                        { id: "437994205", label: "MUTUELLE GENERALE INTERPROFESSIONNELLE" },
                        { id: "438804312", label: "MUTUELLE D'ENTRAIDE DE LA MUTUALITE FRANCAISE" },
                        { id: "442292447", label: "MUTUELLE VERRIERS ET ASSIMILES" },
                        { id: "442294856", label: "UNION MUTUALISTE RETRAITE" },
                        { id: "442449278", label: "MUTUELLE VAROISE DES TRAVAILLEURS DE L'ETAT" },
                        { id: "442489084", label: "MG UNION" },
                        { id: "442634564", label: "MUTUELLE DU PERSONNEL DE LA BANQUE POPULAIRE DU SUD" },
                        { id: "442671830", label: "MUTUELLE DE L'ENSEIGNEMENT CATHOLIQUE DES COTES D'ARMOR" },
                        { id: "442839452", label: "MUTUELLE NAT CONSTRUC ACCED PROPRIETE" },
                        { id: "442907127", label: "ALLIANCE DES MUTUALISTES DU TRANSPORT ET DU SECTEUR SOCIAL - ALMUTRA" },
                        { id: "442930939", label: "MUTUELLE GEODIS" },
                        { id: "442978086", label: "PAVILLON PREVOYANCE" },
                        { id: "443098603", label: "MUTUELLE DES PERSONNELS DU CENTRE HOSPITALIER D'ALES" },
                        { id: "443172507", label: "MUTUELLE DE PREVOYANCE DU PERSONNEL DE LA MACIF" },
                        { id: "443396494", label: "UNION MUTUALISTE DE PREVOYANCE" },
                        { id: "443611504", label: "MUTUELLE D'ENTREPRISE TANIN ET PANNEAUX DE LABRUGUIERE" },
                        { id: "443885355", label: "CYBELE SOLIDARITE" },
                        { id: "444060099", label: "MUTUELLE FACOM" },
                        { id: "444148399", label: "MUTUELLE DU PERSONNEL DE LA CPAM DU SUD FINISTERE" },
                        { id: "444205769", label: "MUTUELLE DE BAGNEAUX" },
                        { id: "444270532", label: "CAISSE DE SOLIDARITE DE L'ARSENAL DE TARBES" },
                        { id: "444270730", label: "MUTUELLE KEOLIS RENNES" },
                        { id: "444424931", label: "MUTUELLE PREVOYANCE ALSACE" },
                        { id: "483041307", label: "TERRITORIA MUTUELLE" },
                        { id: "483747333", label: "RADIANCE MUTUELLE" },
                        { id: "484436811", label: "MNH PREVOYANCE" },
                        { id: "490909454", label: "MUTARIS CAUTION" },
                        { id: "499982098", label: "MGEFI - MUTUELLE GENERALE DE L'ECONOMIE DES FINANCES ET DE L'INDUSTRIE" },
                        { id: "503380081", label: "MUTUELLE UNEO" },
                        { id: "508400629", label: "MFPRECAUTION" },
                        { id: "510778442", label: "MUTUELLE MAE" },
                        { id: "529168007", label: "KLESIA MUT'" },
                        { id: "529219040", label: "MUTEX" },
                        { id: "538518473", label: "HARMONIE MUTUELLE" },
                        { id: "666666666", label: "MUTUELLE DU COMMERCE" },
                        { id: "775558778", label: "MUTUELLE ENTRAIN" },
                        { id: "775559651", label: "MUTUELLE D'ENTREPRISE DU PERSONNEL DE LA SOCIETE DES EAUX DE MARSEILLE" },
                        { id: "775597768", label: "AMELLIS MUTUELLES" },
                        { id: "775606361", label: "MUTUELLE NATIONALE DES HOSPITALIERS ET DES PROFESSIONNELS DE LA SANTE ET DU SOCIAL" },
                        { id: "775627391", label: "AESIO MUTUELLE (ex MUTUELLE APREVA)" },
                        { id: "775641681", label: "MUTEST" },
                        { id: "775657125", label: "SOCIETE MUTUALISTE CHIRURGICALE ET COMPLEMENTAIRE DU PERSONNEL DE LA BANQUE DE FRANCE" },
                        { id: "775657521", label: "MUTUELLE DU MINISTERE DE LA JUSTICE" },
                        { id: "775659378", label: "MUTUELLE DE PREVOYANCE INTERPROFESSIONNELLE" },
                        { id: "775659907", label: "MUTUELLE MIEUX-ETRE" },
                        { id: "775659923", label: "UMEN" },
                        { id: "775662158", label: "ORPHELINAT MUTUALISTE DE LA POLICE NATIONALE PREVOYANCE" },
                        { id: "775666340", label: "ASSOCIATION GENERALE DES MEDECINS DE FRANCE PREVOYANCE" },
                        { id: "775671894", label: "MGP" },
                        { id: "775671902", label: "MUTUELLE DE L'INDUSTRIE DU PETROLE" },
                        { id: "775671951", label: "AVENIR SANTE MUTUELLE" },
                        { id: "775671969", label: "MUTUELLE DU PERSONNEL DU GROUPE RATP" },
                        { id: "775671993", label: "MUTUELLE BLEUE" },
                        { id: "775678550", label: "MUTUELLE GENERALE DES CHEMINOTS" },
                        { id: "775678584", label: "MUTUELLE NATIONALE TERRITORIALE" },
                        { id: "775682164", label: "TUTELAIRE" },
                        { id: "775685340", label: "LA MUTUELLE GENERALE" },
                        { id: "775685365", label: "INTERIALE MUTUELLE" },
                        { id: "775685399", label: "MUTUELLE GENERALE DE L'EDUCATION NATIONALE" },
                        { id: "775691132", label: "LA FRANCE MUTUALISTE" },
                        { id: "775691165", label: "MUTUELLE D'EPARGNE DE RETRAITE ET DE PREVOYANCE CARAC" },
                        { id: "775722655", label: "MOBILITE MUTUELLE" },
                        { id: "776011330", label: "LA FRATERNELLE" },
                        { id: "776346462", label: "SANTEMUT ROANNE" },
                        { id: "776398794", label: "MUTUELLE DES HOSPITALIERS" },
                        { id: "776466963", label: "BPCE MUTUELLE" },
                        { id: "776525610", label: "MUTAME SAVOIE MONT BLANC" },
                        { id: "776531642", label: "MUTUELLE DE FRANCE UNIE" },
                        { id: "776744690", label: "MUTUELLE INTERENTREPRISES DES CAVES DE ROQUEFORT" },
                        { id: "776949760", label: "MUTUELLE NATIONALE DES SAPEURS POMPIERS DE FRANCE" },
                        { id: "776950602", label: "MPOSS" },
                        { id: "776950610", label: "MUTAERO" },
                        { id: "776950677", label: "MUTAMI" },
                        { id: "777749409", label: "MBA MUTUELLE" },
                        { id: "777927120", label: "MUTUELLE VIASANTE" },
                        { id: "778213678", label: "MOS" },
                        { id: "778588111", label: "MUTUELLE D'ENTREPRISE UGINE GUEUGNON & ALZ" },
                        { id: "778847301", label: "SORUAL" },
                        { id: "778868513", label: "LA PREVOYANCE ARTISANALE COMMERCIALE ET SALARIALE" },
                        { id: "778900027", label: "MUTUELLE COMPLEMENTAIRE D'ALSACE" },
                        { id: "779209436", label: "PRECOCIA" },
                        { id: "779445436", label: "MUTUELLE SAMIR" },
                        { id: "779558501", label: "APIVIA MACIF MUTUELLE" },
                        { id: "779846849", label: "SO'LYON MUTUELLE" },
                        { id: "779926294", label: "525EME MUTUELLE D'ENTREPRISES" },
                        { id: "779984921", label: "MUTUELLE DE L'IRSID" },
                        { id: "780004099", label: "ACORIS MUTUELLES" },
                        { id: "780349924", label: "AUBEANE MUTUELLE DE FRANCE" },
                        { id: "780429049", label: "MUTUELLE DU CHAMPAGNE" },
                        { id: "780508073", label: "CCMO MUTUELLE" },
                        { id: "780508081", label: "MUTUELLE DE L'OISE DES AGENTS TERRITORIAUX" },
                        { id: "780915898", label: "MUTAME & PLUS" },
                        { id: "781065412", label: "MUTUELLE DU GRAND PORT MARITIME DU HAVRE" },
                        { id: "781166210", label: "MUTUELLE 403" },
                        { id: "781452511", label: "MACIF" },
                        { id: "781847983", label: "MUTUELLE DU PORT DE BORDEAUX" },
                        { id: "781848221", label: "MUTUELLE LA SOLIDARITE D'AQUITAINE" },
                        { id: "781848239", label: "MUTUELLE DE L'ENTREPRISE CITRAM" },
                        { id: "782416127", label: "MUTUELLE DE FRANCE ALPES DU SUD" },
                        { id: "782814727", label: "MUTUELLE MARSEILLE METROPOLE MUTAME PROVENCE" },
                        { id: "782825343", label: "MUTUELLE DE FRANCE DU LACYDON" },
                        { id: "782825368", label: "MUTUELLE DES SERVICES PUBLICS" },
                        { id: "783005655", label: "MUTUELLE DE LA CORSE" },
                        { id: "783303209", label: "MUTUELLES DU PAYS HAUT" },
                        { id: "783332448", label: "MUTUELLE GENERALE DES ETUDIANTS DE L'EST" },
                        { id: "783376270", label: "GROUPE DES MUTUELLES INDEPENDANTES" },
                        { id: "783747793", label: "CHORALIS - MUTUELLE LE LIBRE CHOIX" },
                        { id: "784117525", label: "MUTUELLE DES AUTEURS ET COMPOSITEURS DRAMATIQUES" },
                        { id: "784227894", label: "MUTUELLE COMPLEMENTAIRE DE LA VILLE DE PARIS DE L'ASSISTANCE PUBLIQUE ET DES ADMINISTRATIONS ANNEXES" },
                        { id: "784275885", label: "MUTUELLE INTERGROUPES D'ENTRAIDE" },
                        { id: "784301434", label: "CDC MUTUELLE" },
                        { id: "784301475", label: "MUTUELLE GENERALE DES AFFAIRES SOCIALES" },
                        { id: "784338600", label: "SOCIETE MUTUALISTE DU PERSONNEL DE LA SNECMA" },
                        { id: "784338618", label: "MCEN - MUTUELLE DES CLERCS ET EMPLOYES DE NOTAIRE" },
                        { id: "784360596", label: "ASSOCIATION NATIONALE DES COLLABORATEURS DE MINISTRES ET DE PARLEMENTAIRES" },
                        { id: "784360661", label: "MUTUELLE DU MONDE COMBATTANT" },
                        { id: "784394363", label: "COMPLEMENTAIRE ASSURANCE MALADIE INTERDEPARTEMENTALE ET FAMILIALE" },
                        { id: "784394413", label: "MUTUELLE FAMILIALE DES CHEMINOTS DE FRANCE" },
                        { id: "784410805", label: "MUTUELLE DU PERSONNEL DU GROUPE SOCIETE GENERALE" },
                        { id: "784410847", label: "MUTUELLE DU GROUPE BNP PARIBAS" },
                        { id: "784442899", label: "MUTUELLE NATIONALE DES FONCTIONNAIRES DES COLLECTIVITES TERRITORIALES" },
                        { id: "784442915", label: "MUTUELLE FAMILIALE" },
                        { id: "784442923", label: "LA SOLIDARITE MUTUALISTE" },
                        { id: "784451569", label: "MUTUELLE INTERGROUPES POLIET ET CIMENT FRANCAIS" },
                        { id: "784492084", label: "FRANCE MUTUELLE" },
                        { id: "784608754", label: "MUTUELLE MMH" },
                        { id: "784647323", label: "LAMIE MUTUELLE" },
                        { id: "784669954", label: "SMI" },
                        { id: "784718207", label: "UNION NATIONALE MUTUALISTE INTERPROFESSIONNELLE" },
                        { id: "784718256", label: "MUTUELLE MALAKOFF HUMANIS" },
                        { id: "784718397", label: "MUTUELLE VALEO" },
                        { id: "785151689", label: "MUTUELLE LES MENAGES PREVOYANTS" },
                        { id: "785196155", label: "MUTUELLE FAMILIALE DES TRAVAILLEURS DU GROUPE SAFRAN" },
                        { id: "785280884", label: "MUTUELLE DES INDUSTRIES AERONAUTIQUES SPATIALES ET CONNEXES" },
                        { id: "788108546", label: "MUTUELLE DES SCOP - MUCS" },
                        { id: "790314017", label: "HARMONIE FONCTION PUBLIQUE" },
                        { id: "851629162", label: "UNMI'MUT" },


                    ]
                })

                await this.seedUpdateStatus("completed")
            }

        } catch (err) {
            console.error(err)
            await this.seedUpdateStatus("error")
        }


    }




}

export const opsV00003Seed = new OpsV00003Seed("OPS_V0003", "Ajout des organismes Mutuelle", 32, "OPS_V0002")

