import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient(
    {
        log: [
            {
                emit: 'stdout',
                level: 'query',
            },
            {
                emit: 'stdout',
                level: 'error',
            },
            {
                emit: 'stdout',
                level: 'info',
            },
            {
                emit: 'stdout',
                level: 'warn',
            },
        ],
    }
)
import { Seed } from "./seedModel"

class OpsV00001Seed extends Seed {
    constructor(
        protected label: string,
        protected description: string,
        protected order: number,
        protected previousLabel: string
    ) {
        super(label, description, order, previousLabel)
    }

    async run() {
        const seedExist = await this.seedIsComplete()
        const previousStatus = await this.previousSeedIsComplete()
        try {
            if (previousStatus && !seedExist) {
                await this.seedUpdateStatus("pending")

                await prisma.dsn_OPS.createMany({
                    data: [
                        {
                            id: '79448723100019',
                            type: 'URSSAF',
                            label: 'URSSAF Provence-Alpes-Côte d\'Azur',
                            address1: '20, avenue Viton',
                            codeZip: '13299',
                            city: 'MARSEILLE CEDEX 20'
                        },
                        {
                            id: '90209799700016',
                            type: 'URSSAF',
                            label: 'URSSAF Normandie',
                            address1: '22, rue d\'Isigny',
                            codeZip: '14045',
                            city: 'CAEN CEDEX 9'
                        },
                        {
                            id: '78299314100038',
                            type: 'URSSAF',
                            label: 'URSSAF de Corse',
                            address1: 'BP 901',
                            codeZip: '20701',
                            city: 'AJACCIO CEDEX 9'
                        },
                        {
                            id: '79471473300019',
                            type: 'URSSAF',
                            label: 'URSSAF Bourgogne',
                            address1: '8, boulevard Georges Clemenceau',
                            codeZip: '21037',
                            city: 'DIJON CEDEX 9'
                        },
                        {
                            id: '79507010100071',
                            type: 'URSSAF',
                            label: 'URSSAF Franche-Comté',
                            address1: '3, Rue de Chatillon',
                            codeZip: '25480',
                            city: 'ECOLE-VALENTIN'
                        },
                        {
                            id: '53514650090018',
                            type: 'URSSAF',
                            label: 'URSSAF Midi-Pyrénées (TGE)',
                            address1: '166, rue Pierre et Marie Curie',
                            codeZip: '31061',
                            city: 'TOULOUSE CEDEX 09'
                        },
                        {
                            id: '53514650000017',
                            type: 'URSSAF',
                            label: 'URSSAF Midi-Pyrénées',
                            address1: '166, rue Pierre et Marie Curie',
                            codeZip: '31061',
                            city: 'TOULOUSE CEDEX 09'
                        },
                        {
                            id: '78877877700011',
                            type: 'URSSAF',
                            label: 'URSSAF Aquitaine',
                            address1: '3, rue Théodore Blanc',
                            codeZip: '33084',
                            city: 'BORDEAUX CEDEX'
                        },
                        {
                            id: '75366412700077',
                            type: 'URSSAF',
                            label: 'URSSAF Languedoc-Roussillon',
                            address1: '35, rue de La Haye',
                            codeZip: '34937',
                            city: 'MONTPELLIER'
                        },
                        {
                            id: '75375957000108',
                            type: 'URSSAF',
                            label: 'URSSAF Bretagne',
                            address1: '6, rue Robert d\'Arbrissel',
                            codeZip: '35052',
                            city: 'RENNES CEDEX 9'
                        },
                        {
                            id: '53510475600015',
                            type: 'URSSAF',
                            label: 'URSSAF Pays de la Loire',
                            address1: '3, rue Gaëtan Rondeau',
                            codeZip: '44000',
                            city: 'NANTES'
                        },
                        {
                            id: '79512003900107',
                            type: 'URSSAF',
                            label: 'URSSAF Centre-Val de Loire',
                            address1: 'Parc du Moulin - 258 boulevard Duhamel du Monceau',
                            codeZip: '45166',
                            city: 'OLIVET CEDEX'
                        },
                        {
                            id: '79512003900081',
                            type: 'URSSAF',
                            label: 'URSSAF Centre (TGE)',
                            address1: 'Place du Général de Gaulle',
                            codeZip: '45000',
                            city: 'ORLEANS'
                        },
                        {
                            id: '50933451200019',
                            type: 'URSSAF',
                            label: 'CCSS de la Lozère',
                            address1: 'Quartier des Carmes',
                            codeZip: '48003',
                            city: 'MENDE CEDEX'
                        },
                        {
                            id: '75285582500010',
                            type: 'URSSAF',
                            label: 'URSSAF Champagne-Ardenne',
                            address1: '202, rue des Capucins',
                            codeZip: '51089',
                            city: 'REIMS CEDEX'
                        },
                        {
                            id: '75333448100011',
                            type: 'URSSAF',
                            label: 'URSSAF Lorraine',
                            address1: '6, rue Pasteur',
                            codeZip: '57032',
                            city: 'METZ CEDEX 1'
                        },
                        {
                            id: '75367340900011',
                            type: 'URSSAF',
                            label: 'URSSAF Nord Pas-de-Calais',
                            address1: '293, avenue du President Hoover',
                            codeZip: '59032',
                            city: 'LILLE CEDEX'
                        },
                        {
                            id: '78366205990022',
                            type: 'URSSAF',
                            label: 'URSSAF Nord Pas-de-Calais (TGE)',
                            address1: '293, avenue du President Hoover',
                            codeZip: '59032',
                            city: 'LILLE CEDEX'
                        },
                        {
                            id: '53513821800016',
                            type: 'URSSAF',
                            label: 'URSSAF Auvergne',
                            address1: '4, rue Patrick Depailler',
                            codeZip: '63054',
                            city: 'CLERMONT FERRAND CEDEX 9'
                        },
                        {
                            id: '75357004300012',
                            type: 'URSSAF',
                            label: 'URSSAF Alsace',
                            address1: '16, rue Contades',
                            codeZip: '67300',
                            city: 'SCHILTIGHEIM'
                        },
                        {
                            id: '79484650100011',
                            type: 'URSSAF',

                            label: 'URSSAF Rhône-Alpes',
                            address1: '6, rue du 19 mars 1962',
                            codeZip: '69200',
                            city: 'VENISSIEUX'
                        },
                        {
                            id: '75366327700014',
                            type: 'URSSAF',
                            label: 'URSSAF Picardie',
                            address1: '1, avenue du Danemark',
                            codeZip: '80000',
                            city: 'AMIENS'
                        },
                        {
                            id: '75364415200013',
                            type: 'URSSAF',
                            label: 'URSSAF Poitou-Charentes',
                            address1: '3, avenue de la Révolution',
                            codeZip: '86046',
                            city: 'POITIERS CEDEX 9'
                        },
                        {
                            id: '75391952100017',
                            type: 'URSSAF',
                            label: 'URSSAF Limousin',
                            address1: '11, rue Camille Pelletan',
                            codeZip: '87047',
                            city: 'LIMOGES CEDEX'
                        },
                        {
                            id: '78861779300013',
                            type: 'URSSAF',
                            label: 'URSSAF Ile-de-France',
                            address1: '',
                            codeZip: '93518',
                            city: 'MONTREUIL CEDEX'
                        },
                        {
                            id: '31457202500307',
                            type: 'URSSAF',

                            label: 'CGSS de la Guadeloupe',
                            address1: 'Quartier de l\'Hôtel de ville',
                            codeZip: '97159',
                            city: 'POINTE A PITRE CEDEX'
                        },
                        {
                            id: '31402496900029',
                            type: 'URSSAF',
                            label: 'CGSS de la Martinique',
                            address1: 'LD Place d\'armes',
                            codeZip: '97210',
                            city: 'LE LAMENTIN'
                        },
                        {
                            id: '31519076900028',
                            type: 'URSSAF',
                            label: 'CGSS de la Guyane',
                            address1: 'Espace Turenne-Radamonthe',
                            codeZip: '97307',
                            city: 'CAYENNE CEDEX'
                        },
                        {
                            id: '31463548300014',
                            type: 'URSSAF',
                            label: 'CGSS de la Réunion',
                            address1: '4, boulevard Doret',
                            codeZip: '97703',
                            city: 'SAINT DENIS'
                        },
                        {
                            id: 'DMSA11',
                            type: 'MSA',
                            label: 'MSA GRAND SUD'
                        },
                        {
                            id: 'DMSA12',
                            type: 'MSA',
                            label: 'MSA MIDI PYRENEES NORD',
                        },
                        {
                            id: 'DMSA13',
                            type: 'MSA',
                            label: 'MSA PROVENCE-AZUR',
                        },
                        {
                            id: 'DMSA14',
                            type: 'MSA',
                            label: 'MSA COTES NORMANDES',
                        },
                        {
                            id: 'DMSA17',
                            type: 'MSA',
                            label: 'MSA CHARENTES',
                        },
                        {
                            id: 'DMSA20',
                            type: 'MSA',
                            label: 'MSA DE LA CORSE',
                        },
                        {
                            id: 'DMSA21',
                            type: 'MSA',
                            label: 'MSA DE BOURGOGNE',
                        },
                        {
                            id: 'DMSA22',
                            type: 'MSA',
                            label: 'MSA ARMORIQUE',
                        },
                        {
                            id: 'DMSA24',
                            type: 'MSA',
                            label: 'MSA DORDOGNE-LOT ET GARONNE',
                        },
                        {
                            id: 'DMSA25',
                            type: 'MSA',
                            label: 'MSA FRANCHE COMTE',
                        },
                        {
                            id: 'DMSA26',
                            type: 'MSA',
                            label: 'MSA ARDECHE-DROME-LOIRE',
                        },
                        {
                            id: 'DMSA27',
                            type: 'MSA',
                            label: 'MSA HAUTE NORMANDIE',
                        },
                        {
                            id: 'DMSA28',
                            type: 'MSA',
                            label: 'MSA BEAUCE-COEUR DE LOIRE',
                        },
                        {
                            id: 'DMSA32',
                            type: 'MSA',
                            label: 'MSA MIDI PYRENEES SUD',
                        },
                        {
                            id: 'DMSA33',
                            type: 'MSA',
                            label: 'MSA GIRONDE',
                        },
                        {
                            id: 'DMSA35',
                            type: 'MSA',
                            label: 'MSA PORTES DE BRETAGNE',
                        },
                        {
                            id: 'DMSA41',
                            type: 'MSA',
                            label: 'MSA BERRY-TOURAINE',
                        },
                        {
                            id: 'DMSA48',
                            type: 'MSA',
                            label: 'MSA LANGUEDOC',
                        },
                        {
                            id: 'DMSA49',
                            type: 'MSA',
                            label: 'MSA MAINE ET LOIRE',
                        },
                        {
                            id: 'DMSA51',
                            type: 'MSA',
                            label: 'MSA MARNE-ARDENNES-MEUSE',
                        },
                        {
                            id: 'DMSA52',
                            type: 'MSA',
                            label: 'MSA SUD CHAMPAGNE',
                        },
                        {
                            id: 'DMSA54',
                            type: 'MSA',
                            label: 'MSA LORRAINE',
                        },
                        {
                            id: 'DMSA59',
                            type: 'MSA',
                            label: 'MSA NORD-PAS DE CALAIS',
                        },
                        {
                            id: 'DMSA63',
                            type: 'MSA',
                            label: 'MSA AUVERGNE',
                        },
                        {
                            id: 'DMSA64',
                            type: 'MSA',
                            label: 'MSA SUD AQUITAINE',
                        },
                        {
                            id: 'DMSA68',
                            type: 'MSA',
                            label: 'MSA ALSACE',
                        },
                        {
                            id: 'DMSA69',
                            type: 'MSA',
                            label: 'MSA AIN-RHONE',
                        },
                        {
                            id: 'DMSA72',
                            type: 'MSA',
                            label: 'MSA MAYENNE-ORNE-SARTHE',
                        },
                        {
                            id: 'DMSA73',
                            type: 'MSA',

                            label: 'MSA ALPES DU NORD',
                        },
                        {
                            id: 'DMSA75',
                            type: 'MSA',
                            label: 'MSA ILE DE FRANCE',
                        },
                        {
                            id: 'DMSA77',
                            type: 'MSA',
                            label: 'MSA SAINT-BARTHELEMY',
                        },
                        {
                            id: 'DMSA80',
                            type: 'MSA',
                            label: 'MSA PICARDIE',
                        },
                        {
                            id: 'DMSA84',
                            type: 'MSA',
                            label: 'MSA ALPES-VAUCLUSE',
                        },
                        {
                            id: 'DMSA85',
                            type: 'MSA',

                            label: 'MSA LOIRE ATLANTIQUE-VENDEE',
                        },
                        {
                            id: 'DMSA86',
                            type: 'MSA',
                            label: 'DMSA86',
                        },
                        {
                            id: 'DMSA87',
                            type: 'MSA',
                            label: 'MSA LIMOUSIN',
                        },
                        { id: "222222222", type: 'Mutuelle', label: "MUTUELLE DE TEST" },
                        { id: "301862769", type: 'Mutuelle', label: "MUTUELLE SMH" },
                        { id: "302476536", type: 'Mutuelle', label: "LA MUTUELLE CATALANE" },
                        { id: "302655766", type: 'Mutuelle', label: "ESPACE MUTUALISTE GIVORDIN" },
                        { id: "302766852", type: 'Mutuelle', label: "MUTUELLE DE LA REGIE DES TRANSPORTS EN COMMUN DE L'AGGLOMERATION TROYENNE" },
                        { id: "302927553", type: 'Mutuelle', label: "APICIL MUTUELLE" },
                        { id: "302976592", type: 'Mutuelle', label: "AVENIR MUTUELLE" },
                        { id: "302981923", type: 'Mutuelle', label: "MUTUELLE DES PROFESSIONS JUDICIAIRES" },
                        { id: "304580228", type: 'Mutuelle', label: "MUTUELLE FAMILIALE DE NORMANDIE" },
                        { id: "308708650", type: 'Mutuelle', label: "MCLR" },
                        { id: "309104099", label: "LA MUTUELLE VERTE", type: 'Mutuelle', },
                        { id: "309244648", label: "MUTUELLE ENTRENOUS", type: 'Mutuelle' },
                        { id: "310259221", label: "MUTUELLE D'IVRY (LA FRATERNELLE)", type: 'Mutuelle' },
                        { id: "311799878", label: "AESIO MUTUELLE (ex ADREA MUTUELLE)", type: 'Mutuelle' },
                        { id: "313309080", label: "LES MUTUELLES LIGERIENNES", type: 'Mutuelle' },
                        { id: "313385882", label: "MUTUELLE ENSEMBLE", type: 'Mutuelle' },
                        { id: "313389157", label: "MUTUELLE D ENTREPRISE DES ETABLISSEMENTS DU BON SAUVEUR", type: 'Mutuelle' },
                        { id: "314559451", label: "MUTUELLE MARE GAILLARD", type: 'Mutuelle' },
                        { id: "314685835", label: "MUTUELLE DES HOPITAUX DE LA VIENNE", type: 'Mutuelle' },
                        { id: "314765546", label: "MUTUELLE DES CHEMINOTS DE LA REGION DE NANTES", type: 'Mutuelle' },
                        { id: "315519231", label: "MUTUELLE LA CHOLETAISE", type: 'Mutuelle' },
                        { id: "315652263", label: "MUTAVIE", type: 'Mutuelle' },
                        { id: "317442176", label: "AESIO MUTUELLE (ex EOVI-MCD MUTUELLE)", type: 'Mutuelle' },
                        { id: "319074779", label: "MUTUELLE CHEMINOTS DU NORD", type: 'Mutuelle' },
                        { id: "320377906", label: "MUTUELLE GENERALE DE PREVOYANCE SOCIALE", type: 'Mutuelle' },
                        { id: "324042621", label: "MUTUELLE DES TRANSPORTS", type: 'Mutuelle' },
                        { id: "330929845", label: "MUTUELLE MFTSV", type: 'Mutuelle' },
                        { id: "331901942", label: "MUTUELLE INTERPROFESSIONNELLE DE PREVOYANCE", type: 'Mutuelle' },
                        { id: "331903757", label: "MUTUELLE ACCIDENTS DE LA CONFEDERATION GENERALE DES OEUVRES LAIQUES", type: 'Mutuelle' },
                        { id: "333212561", label: "MUTUELLE DE PONTOISE", type: 'Mutuelle' },
                        { id: "333333333", label: "MUTUELLE DES PATENTES ET LIBERAUX DE NOUVELLE CALEDONIE", type: 'Mutuelle' },
                        { id: "337682660", label: "MUTUELLE GENERALE DE PREVOYANCE", type: 'Mutuelle' },
                        { id: "339198939", label: "MUTAC", type: 'Mutuelle' },
                        { id: "339358681", label: "MALAKOFF HUMANIS NATIONALE", type: 'Mutuelle' },
                        { id: "340359900", label: "INTEGRANCE", type: 'Mutuelle' },
                        { id: "342211265", label: "MUTUELLES DE LORRAINE", type: 'Mutuelle' },
                        { id: "344304787", label: "UNION DES MUTUELLES DE LA REUNION", type: 'Mutuelle' },
                        { id: "347391948", label: "MUTUELLE DU CHU ET HOPITAUX DU PUY DE DOME", type: 'Mutuelle' },
                        { id: "348099789", label: "MUTUELLE PROVENCE ENTREPRISES", type: 'Mutuelle' },
                        { id: "350873287", label: "MUTUELLE DES TERRITORIAUX ET HOSPITALIERS", type: 'Mutuelle' },
                        { id: "351948237", label: "LA PROBITE", type: 'Mutuelle' },
                        { id: "351956537", label: "MUTUELLE DE L'ENSEIGNEMENT CATHOLIQUE DE L'ANJOU", type: 'Mutuelle' },
                        { id: "351963616", label: "MUTUELLE INTERENTREPRISE ERAM 526", type: 'Mutuelle' },
                        { id: "352291561", label: "MUTUELLE MEUSREC", type: 'Mutuelle' },
                        { id: "352502546", label: "MUTUELLE DU VAL DE SEVRE", type: 'Mutuelle' },
                        { id: "352537369", label: "AMICALE DU PERSONNEL DE FLEURY MICHON SA", type: 'Mutuelle' },
                        { id: "353171440", label: "MIAG - MUTUELLE INTERPROFESSIONNELLE ANTILLE GUYANNE", type: 'Mutuelle' },
                        { id: "379718653", label: "MUTUELLE NATIONALE DES PERSONNELS AIR FRANCE", type: 'Mutuelle' },
                        { id: "382046464", label: "MUTUELLE NATIONALE DU PERSONNEL DES ETABLISSEMENTS MICHELIN", type: 'Mutuelle' },
                        { id: "383143617", label: "SOLIMUT MUTUELLE DE FRANCE", type: 'Mutuelle' },
                        { id: "384253605", label: "MUTLOG GARANTIES", type: 'Mutuelle' },
                        { id: "384513073", label: "MUTUELLE GENERALE DE PREVOYANCE ET D'ASSISTANCE", type: 'Mutuelle' },
                        { id: "388213423", label: "MUTUELLE GENERALE SOLIDARITE DE LA REUNION", type: 'Mutuelle' },
                        { id: "388213712", label: "MUTUELLE FAMILIALE DE LA REUNION", type: 'Mutuelle' },
                        { id: "388887259", label: "MUTUELLE DES ELUS LOCAUX", type: 'Mutuelle' },
                        { id: "390550986", label: "SOCIETE MUTUALISTE DU PERSONNEL ACTIF ET RETRAITE DE LA MARQUE", type: 'Mutuelle' },
                        { id: "390730893", label: "MUTUELLE D'OUEST-FRANCE", type: 'Mutuelle' },
                        { id: "390802619", label: "MUTUELLE LA SECURITE ASTURIENNE", type: 'Mutuelle' },
                        { id: "390820058", label: "MUTUELLE D'ENTREPRISES SCHNEIDER ELECTRIC", type: 'Mutuelle' },
                        { id: "390917953", label: "MUTUELLE DU BATIMENT ET DES TRAVAUX PUBLICS DU SUD EST", type: 'Mutuelle' },
                        { id: "390998466", label: "MUTUELLE SAINT AUBANNAISE", type: 'Mutuelle' },
                        { id: "391036183", label: "MUTUELLE DES SAPEURS POMPIERS DE PARIS", type: 'Mutuelle' },
                        { id: "391322849", label: "MUTUELLE DE LA DEPECHE DU MIDI", type: 'Mutuelle' },
                        { id: "391346236", label: "NUOMA MUTUELLE", type: 'Mutuelle' },
                        { id: "391396397", label: "SOCIETE DE PREVOYANCE MUTUALISTE DU PERSONNEL DE LA BANQUE DE FRANCE", type: 'Mutuelle' },
                        { id: "391398351", label: "MUTUELLE NATIONALE DES CONSTRUCTEURS ET ACCEDANTS A LA PROPRIETE", type: 'Mutuelle' },
                        { id: "391399227", label: "GARANCE", type: 'Mutuelle' },
                        { id: "391399326", label: "MUTUELLE EPC", type: 'Mutuelle' },
                        { id: "391416591", label: "MGDF - MUTUELLE GOODYEAR DUNLOP FRANCE", type: 'Mutuelle' },
                        { id: "391526225", label: "MUTUELLE SANTE EIFFAGE ENERGIE", type: 'Mutuelle' },
                        { id: "391951357", label: "MUTUELLE DU PERSONNEL DES COLLECTIVITES TERRITORIALE DE LA REUNION", type: 'Mutuelle' },
                        { id: "397742958", label: "MUTUELLE DE FRANCE DES HOSPITALIERS", type: 'Mutuelle' },
                        { id: "405390238", label: "MUTUELLE DE FRANCE LOIRE FOREZ", type: 'Mutuelle' },
                        { id: "407879709", label: "SOCIETE MUTUALISTE INTER-ENTREPRISES", type: 'Mutuelle' },
                        { id: "413423005", label: "MUTUELLE LA FRANCE MARITIME", type: 'Mutuelle' },
                        { id: "414494708", label: "SPHERIA VIE", type: 'Mutuelle' },
                        { id: "419049499", label: "ENERGIE MUTUELLE", type: 'Mutuelle' },
                        { id: "419320015", label: "MUTUELLE PREVOYANCE ET DE L'HABITAT DE LA REUNION", type: 'Mutuelle' },
                        { id: "422801910", label: "MUTUELLE DES SPORTIFS", type: 'Mutuelle' },
                        { id: "429873706", label: "BANQUE POPULAIRE MUTUALITE", type: 'Mutuelle' },
                        { id: "430169342", label: "MUTUELLE DES PERSONNELS DU CH MONTPERRIN", type: 'Mutuelle' },
                        { id: "430173336", label: "MUTUELLE DES EMPLOYES TERRITORIAUX DE SAINT RAPHAEL", type: 'Mutuelle' },
                        { id: "430181123", label: "MUTUELLE DES PERSONNELS MARITIMES", type: 'Mutuelle' },
                        { id: "430184507", label: "MUTUELLE DU PERSONNEL DES TRANSPORTS URBAINS DE CANNES - BUS AZUR", type: 'Mutuelle' },
                        { id: "430270116", label: "MUTUELLE DE SAINT JUNIEN ET DES ENVIRONS", type: 'Mutuelle' },
                        { id: "431282581", label: "SOLIMUT MUTUELLE PERSONNELS ORGANISMES SOCIAUX", type: 'Mutuelle' },
                        { id: "431535327", label: "CPAM - SOCIETE MUTUALISTE INTERENTREPRISE DU PERSONNEL DES ORGANISMES SOCIAUX DU LOT", type: 'Mutuelle' },
                        { id: "431643071", label: "MUTUELLE DE LA VERRERIE D'ALBI", type: 'Mutuelle' },
                        { id: "431988021", label: "MUTUELLE EPARGNE RETRAITE", type: 'Mutuelle' },
                        { id: "432162113", label: "MUTUELLE DES ANCIENS DES CHANTIERS LA ROCHELLE-PALLICE", type: 'Mutuelle' },
                        { id: "432456788", label: "MUTUELLE DU PERSONNEL DES PORTS DU DETROIT", type: 'Mutuelle' },
                        { id: "432674281", label: "MUTUELLE AIDE ET SOLIDARITE", type: 'Mutuelle' },
                        { id: "432683787", label: "MUTUELLE DE PREVOYANCE ET DE SANTE", type: 'Mutuelle' },
                        { id: "433087806", label: "MUTUELLE AVENIR SANTE", type: 'Mutuelle' },
                        { id: "434243085", label: "MUTUELLE OCIANE MATMUT", type: 'Mutuelle' },
                        { id: "437732191", label: "SOCIETE MUTUALISTE DU SALEVE", type: 'Mutuelle' },
                        { id: "437994205", label: "MUTUELLE GENERALE INTERPROFESSIONNELLE", type: 'Mutuelle' },
                        { id: "438804312", label: "MUTUELLE D'ENTRAIDE DE LA MUTUALITE FRANCAISE", type: 'Mutuelle' },
                        { id: "442292447", label: "MUTUELLE VERRIERS ET ASSIMILES", type: 'Mutuelle' },
                        { id: "442294856", label: "UNION MUTUALISTE RETRAITE", type: 'Mutuelle' },
                        { id: "442449278", label: "MUTUELLE VAROISE DES TRAVAILLEURS DE L'ETAT", type: 'Mutuelle' },
                        { id: "442489084", label: "MG UNION", type: 'Mutuelle' },
                        { id: "442634564", label: "MUTUELLE DU PERSONNEL DE LA BANQUE POPULAIRE DU SUD", type: 'Mutuelle' },
                        { id: "442671830", label: "MUTUELLE DE L'ENSEIGNEMENT CATHOLIQUE DES COTES D'ARMOR", type: 'Mutuelle' },
                        { id: "442839452", label: "MUTUELLE NAT CONSTRUC ACCED PROPRIETE", type: 'Mutuelle' },
                        { id: "442907127", label: "ALLIANCE DES MUTUALISTES DU TRANSPORT ET DU SECTEUR SOCIAL - ALMUTRA", type: 'Mutuelle' },
                        { id: "442930939", label: "MUTUELLE GEODIS", type: 'Mutuelle' },
                        { id: "442978086", label: "PAVILLON PREVOYANCE", type: 'Mutuelle' },
                        { id: "443098603", label: "MUTUELLE DES PERSONNELS DU CENTRE HOSPITALIER D'ALES", type: 'Mutuelle' },
                        { id: "443172507", label: "MUTUELLE DE PREVOYANCE DU PERSONNEL DE LA MACIF", type: 'Mutuelle' },
                        { id: "443396494", label: "UNION MUTUALISTE DE PREVOYANCE", type: 'Mutuelle' },
                        { id: "443611504", label: "MUTUELLE D'ENTREPRISE TANIN ET PANNEAUX DE LABRUGUIERE", type: 'Mutuelle' },
                        { id: "443885355", label: "CYBELE SOLIDARITE", type: 'Mutuelle' },
                        { id: "444060099", label: "MUTUELLE FACOM", type: 'Mutuelle' },
                        { id: "444148399", label: "MUTUELLE DU PERSONNEL DE LA CPAM DU SUD FINISTERE", type: 'Mutuelle' },
                        { id: "444205769", label: "MUTUELLE DE BAGNEAUX", type: 'Mutuelle' },
                        { id: "444270532", label: "CAISSE DE SOLIDARITE DE L'ARSENAL DE TARBES", type: 'Mutuelle' },
                        { id: "444270730", label: "MUTUELLE KEOLIS RENNES", type: 'Mutuelle' },
                        { id: "444424931", label: "MUTUELLE PREVOYANCE ALSACE", type: 'Mutuelle' },
                        { id: "483041307", label: "TERRITORIA MUTUELLE", type: 'Mutuelle' },
                        { id: "483747333", label: "RADIANCE MUTUELLE", type: 'Mutuelle' },
                        { id: "484436811", label: "MNH PREVOYANCE", type: 'Mutuelle' },
                        { id: "490909454", label: "MUTARIS CAUTION", type: 'Mutuelle' },
                        { id: "499982098", label: "MGEFI - MUTUELLE GENERALE DE L'ECONOMIE DES FINANCES ET DE L'INDUSTRIE", type: 'Mutuelle' },
                        { id: "503380081", label: "MUTUELLE UNEO", type: 'Mutuelle' },
                        { id: "508400629", label: "MFPRECAUTION", type: 'Mutuelle' },
                        { id: "510778442", label: "MUTUELLE MAE", type: 'Mutuelle' },
                        { id: "529168007", label: "KLESIA MUT'", type: 'Mutuelle' },
                        { id: "529219040", label: "MUTEX", type: 'Mutuelle' },
                        { id: "538518473", label: "HARMONIE MUTUELLE", type: 'Mutuelle' },
                        { id: "666666666", label: "MUTUELLE DU COMMERCE", type: 'Mutuelle' },
                        { id: "775558778", label: "MUTUELLE ENTRAIN", type: 'Mutuelle' },
                        { id: "775559651", label: "MUTUELLE D'ENTREPRISE DU PERSONNEL DE LA SOCIETE DES EAUX DE MARSEILLE", type: 'Mutuelle' },
                        { id: "775597768", label: "AMELLIS MUTUELLES", type: 'Mutuelle' },
                        { id: "775606361", label: "MUTUELLE NATIONALE DES HOSPITALIERS ET DES PROFESSIONNELS DE LA SANTE ET DU SOCIAL", type: 'Mutuelle' },
                        { id: "775627391", label: "AESIO MUTUELLE (ex MUTUELLE APREVA)", type: 'Mutuelle' },
                        { id: "775641681", label: "MUTEST", type: 'Mutuelle' },
                        { id: "775657125", label: "SOCIETE MUTUALISTE CHIRURGICALE ET COMPLEMENTAIRE DU PERSONNEL DE LA BANQUE DE FRANCE", type: 'Mutuelle' },
                        { id: "775657521", label: "MUTUELLE DU MINISTERE DE LA JUSTICE", type: 'Mutuelle' },
                        { id: "775659378", label: "MUTUELLE DE PREVOYANCE INTERPROFESSIONNELLE", type: 'Mutuelle' },
                        { id: "775659907", label: "MUTUELLE MIEUX-ETRE", type: 'Mutuelle' },
                        { id: "775659923", label: "UMEN", type: 'Mutuelle' },
                        { id: "775662158", label: "ORPHELINAT MUTUALISTE DE LA POLICE NATIONALE PREVOYANCE", type: 'Mutuelle' },
                        { id: "775666340", label: "ASSOCIATION GENERALE DES MEDECINS DE FRANCE PREVOYANCE", type: 'Mutuelle' },
                        { id: "775671894", label: "MGP", type: 'Mutuelle' },
                        { id: "775671902", label: "MUTUELLE DE L'INDUSTRIE DU PETROLE", type: 'Mutuelle' },
                        { id: "775671951", label: "AVENIR SANTE MUTUELLE", type: 'Mutuelle' },
                        { id: "775671969", label: "MUTUELLE DU PERSONNEL DU GROUPE RATP", type: 'Mutuelle' },
                        { id: "775671993", label: "MUTUELLE BLEUE", type: 'Mutuelle' },
                        { id: "775678550", label: "MUTUELLE GENERALE DES CHEMINOTS", type: 'Mutuelle' },
                        { id: "775678584", label: "MUTUELLE NATIONALE TERRITORIALE", type: 'Mutuelle' },
                        { id: "775682164", label: "TUTELAIRE", type: 'Mutuelle' },
                        { id: "775685340", label: "LA MUTUELLE GENERALE", type: 'Mutuelle' },
                        { id: "775685365", label: "INTERIALE MUTUELLE", type: 'Mutuelle' },
                        { id: "775685399", label: "MUTUELLE GENERALE DE L'EDUCATION NATIONALE", type: 'Mutuelle' },
                        { id: "775691132", label: "LA FRANCE MUTUALISTE", type: 'Mutuelle' },
                        { id: "775691165", label: "MUTUELLE D'EPARGNE DE RETRAITE ET DE PREVOYANCE CARAC", type: 'Mutuelle' },
                        { id: "775722655", label: "MOBILITE MUTUELLE", type: 'Mutuelle' },
                        { id: "776011330", label: "LA FRATERNELLE", type: 'Mutuelle' },
                        { id: "776346462", label: "SANTEMUT ROANNE", type: 'Mutuelle' },
                        { id: "776398794", label: "MUTUELLE DES HOSPITALIERS", type: 'Mutuelle' },
                        { id: "776466963", label: "BPCE MUTUELLE", type: 'Mutuelle' },
                        { id: "776525610", label: "MUTAME SAVOIE MONT BLANC", type: 'Mutuelle' },
                        { id: "776531642", label: "MUTUELLE DE FRANCE UNIE", type: 'Mutuelle' },
                        { id: "776744690", label: "MUTUELLE INTERENTREPRISES DES CAVES DE ROQUEFORT", type: 'Mutuelle' },
                        { id: "776949760", label: "MUTUELLE NATIONALE DES SAPEURS POMPIERS DE FRANCE", type: 'Mutuelle' },
                        { id: "776950602", label: "MPOSS", type: 'Mutuelle' },
                        { id: "776950610", label: "MUTAERO", type: 'Mutuelle' },
                        { id: "776950677", label: "MUTAMI", type: 'Mutuelle' },
                        { id: "777749409", label: "MBA MUTUELLE", type: 'Mutuelle' },
                        { id: "777927120", label: "MUTUELLE VIASANTE", type: 'Mutuelle' },
                        { id: "778213678", label: "MOS", type: 'Mutuelle' },
                        { id: "778588111", label: "MUTUELLE D'ENTREPRISE UGINE GUEUGNON & ALZ", type: 'Mutuelle' },
                        { id: "778847301", label: "SORUAL", type: 'Mutuelle' },
                        { id: "778868513", label: "LA PREVOYANCE ARTISANALE COMMERCIALE ET SALARIALE", type: 'Mutuelle' },
                        { id: "778900027", label: "MUTUELLE COMPLEMENTAIRE D'ALSACE", type: 'Mutuelle' },
                        { id: "779209436", label: "PRECOCIA", type: 'Mutuelle' },
                        { id: "779445436", label: "MUTUELLE SAMIR", type: 'Mutuelle' },
                        { id: "779558501", label: "APIVIA MACIF MUTUELLE", type: 'Mutuelle' },
                        { id: "779846849", label: "SO'LYON MUTUELLE", type: 'Mutuelle' },
                        { id: "779926294", label: "525EME MUTUELLE D'ENTREPRISES", type: 'Mutuelle' },
                        { id: "779984921", label: "MUTUELLE DE L'IRSID", type: 'Mutuelle' },
                        { id: "780004099", label: "ACORIS MUTUELLES", type: 'Mutuelle' },
                        { id: "780349924", label: "AUBEANE MUTUELLE DE FRANCE", type: 'Mutuelle' },
                        { id: "780429049", label: "MUTUELLE DU CHAMPAGNE", type: 'Mutuelle' },
                        { id: "780508073", label: "CCMO MUTUELLE", type: 'Mutuelle' },
                        { id: "780508081", label: "MUTUELLE DE L'OISE DES AGENTS TERRITORIAUX", type: 'Mutuelle' },
                        { id: "780915898", label: "MUTAME & PLUS", type: 'Mutuelle' },
                        { id: "781065412", label: "MUTUELLE DU GRAND PORT MARITIME DU HAVRE", type: 'Mutuelle' },
                        { id: "781166210", label: "MUTUELLE 403", type: 'Mutuelle' },
                        { id: "781452511", label: "MACIF", type: 'Mutuelle' },
                        { id: "781847983", label: "MUTUELLE DU PORT DE BORDEAUX", type: 'Mutuelle' },
                        { id: "781848221", label: "MUTUELLE LA SOLIDARITE D'AQUITAINE", type: 'Mutuelle' },
                        { id: "781848239", label: "MUTUELLE DE L'ENTREPRISE CITRAM", type: 'Mutuelle' },
                        { id: "782416127", label: "MUTUELLE DE FRANCE ALPES DU SUD", type: 'Mutuelle' },
                        { id: "782814727", label: "MUTUELLE MARSEILLE METROPOLE MUTAME PROVENCE", type: 'Mutuelle' },
                        { id: "782825343", label: "MUTUELLE DE FRANCE DU LACYDON", type: 'Mutuelle' },
                        { id: "782825368", label: "MUTUELLE DES SERVICES PUBLICS", type: 'Mutuelle' },
                        { id: "783005655", label: "MUTUELLE DE LA CORSE", type: 'Mutuelle' },
                        { id: "783303209", label: "MUTUELLES DU PAYS HAUT", type: 'Mutuelle' },
                        { id: "783332448", label: "MUTUELLE GENERALE DES ETUDIANTS DE L'EST", type: 'Mutuelle' },
                        { id: "783376270", label: "GROUPE DES MUTUELLES INDEPENDANTES", type: 'Mutuelle' },
                        { id: "783747793", label: "CHORALIS - MUTUELLE LE LIBRE CHOIX", type: 'Mutuelle' },
                        { id: "784117525", label: "MUTUELLE DES AUTEURS ET COMPOSITEURS DRAMATIQUES", type: 'Mutuelle' },
                        { id: "784227894", label: "MUTUELLE COMPLEMENTAIRE DE LA VILLE DE PARIS DE L'ASSISTANCE PUBLIQUE ET DES ADMINISTRATIONS ANNEXES", type: 'Mutuelle' },
                        { id: "784275885", label: "MUTUELLE INTERGROUPES D'ENTRAIDE", type: 'Mutuelle' },
                        { id: "784301434", label: "CDC MUTUELLE", type: 'Mutuelle' },
                        { id: "784301475", label: "MUTUELLE GENERALE DES AFFAIRES SOCIALES", type: 'Mutuelle' },
                        { id: "784338600", label: "SOCIETE MUTUALISTE DU PERSONNEL DE LA SNECMA", type: 'Mutuelle' },
                        { id: "784338618", label: "MCEN - MUTUELLE DES CLERCS ET EMPLOYES DE NOTAIRE", type: 'Mutuelle' },
                        { id: "784360596", label: "ASSOCIATION NATIONALE DES COLLABORATEURS DE MINISTRES ET DE PARLEMENTAIRES", type: 'Mutuelle' },
                        { id: "784360661", label: "MUTUELLE DU MONDE COMBATTANT", type: 'Mutuelle' },
                        { id: "784394363", label: "COMPLEMENTAIRE ASSURANCE MALADIE INTERDEPARTEMENTALE ET FAMILIALE", type: 'Mutuelle' },
                        { id: "784394413", label: "MUTUELLE FAMILIALE DES CHEMINOTS DE FRANCE", type: 'Mutuelle' },
                        { id: "784410805", label: "MUTUELLE DU PERSONNEL DU GROUPE SOCIETE GENERALE", type: 'Mutuelle' },
                        { id: "784410847", label: "MUTUELLE DU GROUPE BNP PARIBAS", type: 'Mutuelle' },
                        { id: "784442899", label: "MUTUELLE NATIONALE DES FONCTIONNAIRES DES COLLECTIVITES TERRITORIALES", type: 'Mutuelle' },
                        { id: "784442915", label: "MUTUELLE FAMILIALE", type: 'Mutuelle' },
                        { id: "784442923", label: "LA SOLIDARITE MUTUALISTE", type: 'Mutuelle' },
                        { id: "784451569", label: "MUTUELLE INTERGROUPES POLIET ET CIMENT FRANCAIS", type: 'Mutuelle' },
                        { id: "784492084", label: "FRANCE MUTUELLE", type: 'Mutuelle' },
                        { id: "784608754", label: "MUTUELLE MMH", type: 'Mutuelle' },
                        { id: "784647323", label: "LAMIE MUTUELLE", type: 'Mutuelle' },
                        { id: "784669954", label: "SMI", type: 'Mutuelle' },
                        { id: "784718207", label: "UNION NATIONALE MUTUALISTE INTERPROFESSIONNELLE", type: 'Mutuelle' },
                        { id: "784718256", label: "MUTUELLE MALAKOFF HUMANIS", type: 'Mutuelle' },
                        { id: "784718397", label: "MUTUELLE VALEO", type: 'Mutuelle' },
                        { id: "785151689", label: "MUTUELLE LES MENAGES PREVOYANTS", type: 'Mutuelle' },
                        { id: "785196155", label: "MUTUELLE FAMILIALE DES TRAVAILLEURS DU GROUPE SAFRAN", type: 'Mutuelle' },
                        { id: "785280884", label: "MUTUELLE DES INDUSTRIES AERONAUTIQUES SPATIALES ET CONNEXES", type: 'Mutuelle' },
                        { id: "788108546", label: "MUTUELLE DES SCOP - MUCS", type: 'Mutuelle' },
                        { id: "790314017", label: "HARMONIE FONCTION PUBLIQUE", type: 'Mutuelle' },
                        { id: "P0002", label: "AGRI PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0223", label: "CPCEA", type: 'Prévoyance' },
                        { id: "P0395", label: "MALAKOFF MEDERIC PREVOYANCE (ex CAPREVAL)", type: 'Prévoyance' },
                        { id: "P0675", label: "IPSEC", type: 'Prévoyance' },
                        { id: "P0826", label: "KERIALIS (ex-CREPA)", type: 'Prévoyance' },
                        { id: "P0832", label: "CARCO", type: 'Prévoyance' },
                        { id: "P0914", label: "BTP PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0921", label: "CIPREV", type: 'Prévoyance' },
                        { id: "P0930", label: "APGIS", type: 'Prévoyance' },
                        { id: "P0942", label: "AG2R PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0945", label: "ARPEGE PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0947", label: "UNIPREVOYANCE", type: 'Prévoyance' },
                        { id: "P0954", label: "IPRIAC", type: 'Prévoyance' },
                        { id: "P0958", label: "IRP AUTO Prévoyance-Santé", type: 'Prévoyance' },
                        { id: "P0959", label: "KLESIA PREVOYANCE (ex-IPGM)", type: 'Prévoyance' },
                        { id: "P0971", label: "CARCEPT PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0972", label: "INPR", type: 'Prévoyance' },
                        { id: "P0978", label: "CARPILIG PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0979", label: "IPECA PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0983", label: "AUDIENS PREVOYANCE", type: 'Prévoyance' },
                        { id: "P0990", label: "CRP-BTP", type: 'Prévoyance' },
                        { id: "P0997", label: "IPBP", type: 'Prévoyance' },
                        { id: "P1003", label: "IRCEM PREVOYANCE", type: 'Prévoyance' },
                        { id: "P1016", label: "KLESIA PREVOYANCE (ex-OREPA-Prévoyance)", type: 'Prévoyance' },
                        { id: "P1020", label: "CAISSE REUNIONNAISE DE PREVOYANCE (CRP)", type: 'Prévoyance' },
                        { id: "P1022", label: "CAPSSA", type: 'Prévoyance' },
                        { id: "P1030", label: "HUMANIS PREVOYANCE (fusionnant APRI/IONIS/NOVALIS/TAITBOUT/CAPAVES prévoyance)", type: 'Prévoyance' },
                        { id: "P1031", label: "APICIL PREVOYANCE", type: 'Prévoyance' },
                        { id: "P1033", label: "CGPCE", type: 'Prévoyance' },
                        { id: "P1035", label: "CCPMA PREVOYANCE", type: 'Prévoyance' },
                        { id: "P1330", label: "A2VIP (ex B2V Prévoyance)", type: 'Prévoyance' },
                        { id: "P2001", label: "MIEL GROUPE MALAKOFF HUMANIS", type: 'Prévoyance' },
                        { id: "P2002", label: "SMATIS Mutuelle", type: 'Prévoyance' },
                        { id: "P2003", label: "MCCI", type: 'Prévoyance' },
                        { id: "P2005", label: "MUTUELLE BOISSIERE", type: 'Prévoyance' },
                        { id: "P3001", label: "RSBP", type: 'Prévoyance' },
                        { id: "P3008", label: "CPCEA RETRAITE SUPPLEMENTAIRE", type: 'Prévoyance' },
                        { id: "P3009", label: "CCPMA RETRAITE SUPPLEMENTAIRE", type: 'Prévoyance' },
                        { id: "P3010", label: "PRODIGEO", type: 'Prévoyance' },
                    ]
                })


                await this.seedUpdateStatus("completed")
            }

        } catch (err) {
            console.error(err)
            await this.seedUpdateStatus("error")
        }


    }


}
export const opsV00001Seed = new OpsV00001Seed("OPS_V0001", "Création des organismes de protection social", 5, "RATE_AT_V0001")